// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2f4g7zlFUkpfyeHzlqCMXSi8JmPARumU',
    appId: '1:182093358828:web:3c8075fa2e0c01bccf67c9',
    messagingSenderId: '182093358828',
    projectId: 'authenticate-40b66',
    authDomain: 'authenticate-40b66.firebaseapp.com',
    storageBucket: 'authenticate-40b66.firebasestorage.app',
    measurementId: 'G-LNVX7DRGJP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0yNEizBBCvCWH30kDSe8nIdqvN4beVgI',
    appId: '1:182093358828:android:84cb38e6571cee1ecf67c9',
    messagingSenderId: '182093358828',
    projectId: 'authenticate-40b66',
    storageBucket: 'authenticate-40b66.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOPhpdkFufrrKUEUeIgOgA5uN5nSQW1hk',
    appId: '1:182093358828:ios:a06a6d995d024d38cf67c9',
    messagingSenderId: '182093358828',
    projectId: 'authenticate-40b66',
    storageBucket: 'authenticate-40b66.firebasestorage.app',
    iosBundleId: 'com.example.authenticate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOPhpdkFufrrKUEUeIgOgA5uN5nSQW1hk',
    appId: '1:182093358828:ios:a06a6d995d024d38cf67c9',
    messagingSenderId: '182093358828',
    projectId: 'authenticate-40b66',
    storageBucket: 'authenticate-40b66.firebasestorage.app',
    iosBundleId: 'com.example.authenticate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2f4g7zlFUkpfyeHzlqCMXSi8JmPARumU',
    appId: '1:182093358828:web:31354d900e4b4970cf67c9',
    messagingSenderId: '182093358828',
    projectId: 'authenticate-40b66',
    authDomain: 'authenticate-40b66.firebaseapp.com',
    storageBucket: 'authenticate-40b66.firebasestorage.app',
    measurementId: 'G-W838W8RXEX',
  );
}
